import { CategoryData } from '../types';

export const filmovi: CategoryData = {
  label: 'Filmovi i Serije',
  sentences: [
    { crew: 'Koji film bi gledao ponovo bez razmišljanja?', impostor: 'Koji film nikada više ne bi gledao?' },
    { crew: 'Opiši svoj omiljeni filmski žanr.', impostor: 'Opiši filmski žanr koji najmanje voliš.' },
    { crew: 'Ko je tvoj omiljeni filmski lik?', impostor: 'Ko je tvoj omiljeni filmski negativac?' },
    { crew: 'Koji film te je najviše nasmejao?', impostor: 'Koji film te je najviše uplašio?' },
    { crew: 'Da snimaš film, o čemu bi bio?', impostor: 'Da pišeš knjigu, o čemu bi bila?' },
    { crew: 'Koja filmska scena ti je ostala urezana u sećanje?', impostor: 'Koja filmska scena te je najviše zbunila?' },
    { crew: 'Koji glumac može da spasi i najgori film?', impostor: 'Koji glumac može da uništi i najbolji film?' },
    { crew: 'Koju seriju si binge-ovao u jednom dahu?', impostor: 'Koju seriju si ostavio posle prve epizode?' },
    { crew: 'Koji film bi preporučio strancu da razume tvoju kulturu?', impostor: 'Koji film bi sakrio od stranca da ne bi pogrešno shvatio tvoju kulturu?' },
    { crew: 'Da živiš u univerzumu jednog filma, koji bi bio?', impostor: 'Da si zarobljen u horor filmu, koji bi bio?' },
    { crew: 'Koji filmski par je po tebi najbolji?', impostor: 'Koji filmski par ti deluje najlažnije?' },
    { crew: 'Koji soundtrack filma slušaš i kad ne gledaš film?', impostor: 'Koja filmska muzika ti ide na živce?' },
    { crew: 'Koji reditelj nikada ne razočara?', impostor: 'Koji reditelj uvek razočara?' },
    { crew: 'Koji film je bolji od knjige?', impostor: 'Koji film je uništio savršenu knjigu?' },
    { crew: 'Da si filmski kritičar, kako bi ocenio poslednji film koji si gledao?', impostor: 'Da si filmski producent, koji žanr nikada ne bi finansirao?' },
    { crew: 'Koja serija ima najbolji pilot?', impostor: 'Koja serija ima najgori finale?' },
    { crew: 'Koji film gledaš svake nove godine?', impostor: 'Koji film gledaš kad si bolestan?' },
    { crew: 'Da možeš da zaboraviš jedan film da bi ga ponovo gledao, koji bi bio?', impostor: 'Da možeš da izbrišeš jedan film iz istorije, koji bi bio?' },
    { crew: 'Koji filmski lik te podseća na sebe?', impostor: 'Koji filmski lik te podseća na najboljeg druga?' },
    { crew: 'Opiši savršeno filmsko veče.', impostor: 'Opiši najgore filmsko iskustvo u bioskopu.' },
    { crew: 'Koji film je po tebi remek-delo a drugi se ne slažu?', impostor: 'Koji film svi hvale a tebi je dosadan?' },
    { crew: 'Da si statista u nekom filmu, u kom bi bio?', impostor: 'Da si sporedni lik u nekoj seriji, u kojoj bi bio?' },
    { crew: 'Koji serijal bi trebalo da dobije još nastavaka?', impostor: 'Koji serijal bi trebalo da je stao na prvom delu?' },
    { crew: 'Koji film te je iznenadio krajem?', impostor: 'Koji film si pogodio kraj od samog početka?' },
    { crew: 'Koja animirana serija je zapravo za odrasle?', impostor: 'Koja serija za odrasle je zapravo detinjasta?' },
    { crew: 'Koji film bi pogledao sa celom porodicom?', impostor: 'Koji film nikada ne bi gledao sa roditeljima?' },
    { crew: 'Da snimaš dokumentarac, o čemu bi bio?', impostor: 'Da snimaš reality show, kakav bi bio format?' },
    { crew: 'Koji filmski zlikovac ti je zapravo simpatičan?', impostor: 'Koji filmski heroj te zapravo nervira?' },
    { crew: 'Koja je najbolja filmska adaptacija video igre?', impostor: 'Koja je najgora filmska adaptacija bilo čega?' },
    { crew: 'Koji film te je naterao da razmišljaš danima?', impostor: 'Koji film si zaboravio čim si izašao iz bioskopa?' },
    { crew: 'Da imaš bioskop, koje filmove bi prikazivao?', impostor: 'Da imaš streaming platformu, čime bi se razlikovala?' },
    { crew: 'Koji glumac bi trebalo da dobije Oskara a nikada nije?', impostor: 'Koji glumac je dobio Oskara a nije zaslužio?' },
    { crew: 'Koja je najbolja trilogija svih vremena?', impostor: 'Koji nastavak je bio potpuno nepotreban?' },
    { crew: 'Koji film bi preporučio nekome ko je tužan?', impostor: 'Koji film nikada ne bi gledao kad si tužan?' },
    { crew: 'Da si u žiriju filmskog festivala, šta bi tražio?', impostor: 'Da si u žiriju talent showa, šta bi ocenjivao?' },
    { crew: 'Koji film ima najbolju prvu scenu?', impostor: 'Koji film ima najgoru završnu scenu?' },
    { crew: 'Koja serija je imala najbolji character development?', impostor: 'Koji serijski lik se potpuno promenio na gore?' },
    { crew: 'Koji film je definisao tvoje detinjstvo?', impostor: 'Koji film je definisao tvoje tinejdžerske godine?' },
    { crew: 'Da snimaš komediju, ko bi ti bio glavna zvezda?', impostor: 'Da snimaš akcioni film, ko bi ti bio glavna zvezda?' },
    { crew: 'Koji film ti je promenio perspektivu o nečemu?', impostor: 'Koji film ti je potvrdio nešto u šta si već verovao?' },
  ],
  concepts: [
    { crew: 'Harry Potter', impostor: 'Dečak koji je promenio žanr za celu generaciju' },
    { crew: 'Titanik', impostor: 'Tragedija koja te natera da plačeš svaki put' },
    { crew: 'Osvetnici', impostor: 'Kad imaš previše heroja za jedan poster' },
    { crew: 'Kralj Lavova', impostor: 'Životinjsko carstvo sa porodičnom dramom' },
    { crew: 'Matriks', impostor: 'Film posle kog preispituješ stvarnost' },
    { crew: 'Zvezdani Ratovi', impostor: 'Porodični problemi u svemiru' },
    { crew: 'Gospodar Prstenova', impostor: 'Putovanje od kog te bole noge samo od gledanja' },
    { crew: 'Forrest Gump', impostor: 'Čovek koji slučajno pravi istoriju' },
    { crew: 'Joker', impostor: 'Negativac kome saosećaš' },
    { crew: 'Betmen', impostor: 'Bogataš sa čudnim hobijem' },
    { crew: 'Parazit', impostor: 'Film gde ne znaš kome da navijаš' },
    { crew: 'Inception', impostor: 'Nešto posle čega ti treba objašnjenje' },
    { crew: 'Shrek', impostor: 'Ružnoća kao supermoć' },
    { crew: 'Rocky', impostor: 'Priča u kojoj poraz izgleda kao pobeda' },
    { crew: 'Gladijator', impostor: 'Osveta koja traje dva sata' },
    { crew: 'Krsteni Otac', impostor: 'Porodični biznis koji ne želiš da naslediš' },
    { crew: 'Šest čula', impostor: 'Film čiji kraj menja sve što si gledao' },
    { crew: 'Interstellar', impostor: 'Ljubav koja savija prostor i vreme' },
    { crew: 'Jaws', impostor: 'Razlog da ne uđeš u vodu' },
    { crew: 'E.T.', impostor: 'Drugarstvo koje ne poznaje granice' },
    { crew: 'Crni Panter', impostor: 'Skriveno bogatstvo koje menja pravila' },
    { crew: 'Up', impostor: 'Prvih 10 minuta te slomi' },
    { crew: 'Spider-Man', impostor: 'Tinejdžer sa problemima na kvadrat' },
    { crew: 'Mulan', impostor: 'Kad se sakriješ da bi bio svoj' },
    { crew: 'Fight Club', impostor: 'Film o kome se ne priča' },
    { crew: 'Pobeg iz Šošenka', impostor: 'Strpljenje koje se isplati' },
    { crew: 'Frozen', impostor: 'Pesma koju ne možeš da izbacиш iz glave' },
    { crew: 'John Wick', impostor: 'Kad te pogrešna stvar naljuti' },
    { crew: 'Društvo mrtvih pesnika', impostor: 'Učitelj kakav ti nikad neće predavati' },
    { crew: 'Blade Runner', impostor: 'Kiša i neonska pitanja o duši' },
    { crew: 'Toy Story', impostor: 'Igračke sa egzistencijalnom krizom' },
    { crew: 'Alien', impostor: 'U svemiru niko ne čuje da vrištiš' },
    { crew: 'Zoolander', impostor: 'Lepota bez mozga' },
    { crew: 'Scarface', impostor: 'Uspeh koji dolazi sa velikim padom' },
    { crew: 'Hangover', impostor: 'Jutro posle najgore noći' },
    { crew: 'Coco', impostor: 'Muzika koja povezuje žive i mrtve' },
    { crew: 'Die Hard', impostor: 'Praznični film o kome se ljudi svađaju' },
    { crew: 'Avatar', impostor: 'Plavo čudo koje si video ali ne pamtiš priču' },
    { crew: 'Čarobnjak iz Oza', impostor: 'Put kući koji dugo traje' },
    { crew: 'La La Land', impostor: 'Ples između snova i stvarnosti' },
  ],
};
