import { CategoryData } from '../types';

export const hrana: CategoryData = {
  label: 'Hrana',
  sentences: [
    { crew: 'Koje jelo bi spremio za posebnu priliku?', impostor: 'Koje jelo nikada ne bi spremio za goste?' },
    { crew: 'Šta najradije jedeš za doručak?', impostor: 'Šta najradije jedeš za večeru?' },
    { crew: 'Opiši ukus svog omiljenog voća.', impostor: 'Opiši ukus svog omiljenog povrća.' },
    { crew: 'Koji je tvoj omiljeni brzi obrok?', impostor: 'Koji brzi obrok ne podnosiš?' },
    { crew: 'Da moraš da jedeš samo jednu hranu zauvek, šta bi izabrao?', impostor: 'Da moraš da piješ samo jedan napitak zauvek, šta bi izabrao?' },
    { crew: 'Koje jelo bi pojeo za poslednji obrok u životu?', impostor: 'Koje jelo bi pojeo na prvom dejtu?' },
    { crew: 'Opiši najgoru stvar koju si ikada probao.', impostor: 'Opiši najčudniju stvar koju si ikada probao.' },
    { crew: 'Koji začin koristiš za skoro sve?', impostor: 'Koji začin nikada ne koristiš?' },
    { crew: 'Da otvaraš restoran, kakva bi bila kuhinja?', impostor: 'Da otvaraš poslastičarnicu, šta bi bio glavni proizvod?' },
    { crew: 'Koje jelo te podseća na detinjstvo?', impostor: 'Koje jelo te podseća na leto?' },
    { crew: 'Šta misliš da kuvaš bolje od većine ljudi?', impostor: 'Šta nikada ne bi pokušao sam da skuvaš?' },
    { crew: 'Koji je tvoj comfort food kad si tužan?', impostor: 'Šta jedeš kad slaviš nešto?' },
    { crew: 'Opiši savršen sendvič.', impostor: 'Opiši savršen burger.' },
    { crew: 'Koju hranu uvek imaš u frižideru?', impostor: 'Koju hranu uvek imaš u zamrzivaču?' },
    { crew: 'Da si kuvar u takmičenju, šta bi spremio za finale?', impostor: 'Da si sudija u takmičenju kuvanja, šta bi najstrože ocenjivao?' },
    { crew: 'Koja hrana te iznenađuje koliko je skupa?', impostor: 'Koja hrana te iznenađuje koliko je jeftina?' },
    { crew: 'Koji je najbolji street food koji si probao?', impostor: 'Koji je najbolji desert koji si probao?' },
    { crew: 'Koja hrana je po tebi precenjena?', impostor: 'Koja hrana je po tebi potcenjena?' },
    { crew: 'Opiši obrok koji bi spremio za nekoga koga voliš.', impostor: 'Opiši obrok koji bi spremio da impresioniraš šefa.' },
    { crew: 'Šta nikada ne bi kombinovao u istom jelu?', impostor: 'Šta uvek kombinuješ a drugi misle da je čudno?' },
    { crew: 'Koju hranu nisi voleo kao dete a sad obožavaš?', impostor: 'Koju hranu si obožavao kao dete a sad ne podnosiš?' },
    { crew: 'Koji je tvoj omiljeni način pripreme jaja?', impostor: 'Koji je tvoj omiljeni način pripreme krompira?' },
    { crew: 'Da praviš savršen piknik, šta bi poneo?', impostor: 'Da praviš savršen roštilj, šta bi stavio na žar?' },
    { crew: 'Koji napitak te drži budnim?', impostor: 'Koji napitak te uspavljuje?' },
    { crew: 'Koja hrana miriše bolje nego što je na ukus?', impostor: 'Koja hrana izgleda bolje nego što je na ukus?' },
    { crew: 'Iz koje zemlje bi naručio hranu da možeš?', impostor: 'Iz koje kuhinje ne bi probao ništa?' },
    { crew: 'Koji je tvoj guilty pleasure u hrani?', impostor: 'Šta tajno jedeš kad niko ne gleda?' },
    { crew: 'Da imaš neograničen budžet za večeru, gde bi otišao?', impostor: 'Da moraš da spremiš večeru za 500 dinara, šta bi napravio?' },
    { crew: 'Koja hrana uvek poboljša loš dan?', impostor: 'Koja hrana uvek razočara kad je naručiš?' },
    { crew: 'Šta bi jeo pre treninga?', impostor: 'Šta bi jeo posle treninga?' },
    { crew: 'Koji topping na pici je svetinja?', impostor: 'Koji topping na pici je zločin?' },
    { crew: 'Da moraš da preživiš na jednom voću, koje bi izabrao?', impostor: 'Da moraš da preživiš na jednom povrću, koje bi izabrao?' },
    { crew: 'Opiši savršenu čokoladnu tortu.', impostor: 'Opiši savršen kolač od voća.' },
    { crew: 'Šta ti fali kad si van Srbije?', impostor: 'Šta iz inostranstva bi voleo da uvek bude dostupno ovde?' },
    { crew: 'Koji obrok ne preskačeš nikada?', impostor: 'Koji obrok preskočiš skoro svaki dan?' },
    { crew: 'Koja hrana je po tebi umetnost?', impostor: 'Koja hrana je po tebi čist marketing?' },
    { crew: 'Šta bi kuvao da ti dolazi 20 ljudi na žurku?', impostor: 'Šta bi kuvao da imaš romantičnu večeru za dvoje?' },
    { crew: 'Koji sos ide uz sve?', impostor: 'Koji sos ne bi stavio ni na šta?' },
    { crew: 'Da imaš food truck, šta bi prodavao?', impostor: 'Da imaš pekaru, šta bi bilo u ponudi?' },
    { crew: 'Koji je najjači domaći specijalitet?', impostor: 'Koji domaći specijalitet te nikad nije oduševio?' },
  ],
  concepts: [
    { crew: 'Pizza', impostor: 'Nešto što svako prilagođava sebi' },
    { crew: 'Sladoled', impostor: 'Sreća koja se topi' },
    { crew: 'Palačinke', impostor: 'Bolje kad ih neko drugi napravi' },
    { crew: 'Čokolada', impostor: 'Razlog za grižu savesti' },
    { crew: 'Pljeskavica', impostor: 'Razlog za red na kiši' },
    { crew: 'Kafa', impostor: 'Bez ovoga jutro ne postoji' },
    { crew: 'Banana', impostor: 'Uvek sazre u pogrešnom trenutku' },
    { crew: 'Med', impostor: 'Zlatno i lekovito' },
    { crew: 'Jogurt', impostor: 'Uvek prisutno a nikad glavna uloga' },
    { crew: 'Lubenica', impostor: 'Letnji razlog za fleke na majici' },
    { crew: 'Hleb', impostor: 'Bez ovoga obrok deluje prazan' },
    { crew: 'Kečap', impostor: 'Menja sve u šta ga staviš' },
    { crew: 'Paradajz', impostor: 'Voće koje se pretvara da je nešto drugo' },
    { crew: 'Čips', impostor: 'Nemoguće pojesti samo jedan' },
    { crew: 'Avokado', impostor: 'Skup trend koji podeli ljude' },
    { crew: 'Limun', impostor: 'Kiselo ali neophodno' },
    { crew: 'Sarma', impostor: 'Razlog za porodični ručak' },
    { crew: 'Burek', impostor: 'Razlog za regionalnu raspravu' },
    { crew: 'Pečenje', impostor: 'Čeka se satima, pojede za minute' },
    { crew: 'Supa', impostor: 'Lek koji bake propisuju za sve' },
    { crew: 'Giros', impostor: 'Nešto što se jede u 3 ujutru' },
    { crew: 'Kokice', impostor: 'Bez ovoga iskustvo nije kompletno' },
    { crew: 'Torta', impostor: 'Pojavljuje se samo na proslavama' },
    { crew: 'Ćevapi', impostor: 'Nešto što se broji, ne meri' },
    { crew: 'Jabuka', impostor: 'Tera doktora od kuće' },
    { crew: 'Sir', impostor: 'Što je stariji, to je bolji' },
    { crew: 'Ljuta paprika', impostor: 'Izazov koji prihvataš samo jednom' },
    { crew: 'Pomfrit', impostor: 'Najbolji deo svakog obroka' },
    { crew: 'Kroasan', impostor: 'Izgovor da jedeš maslo za doručak' },
    { crew: 'Suši', impostor: 'Hrana koja izgleda kao umetnost' },
    { crew: 'Jaje', impostor: 'Može na sto načina a uvek isto' },
    { crew: 'Beli luk', impostor: 'Tera i bolest i ljude od tebe' },
    { crew: 'Puter', impostor: 'Tajna svakog dobrog recepta' },
    { crew: 'Džem', impostor: 'Sećanje na bakinu kuhinju' },
    { crew: 'Testenina', impostor: 'Univerzalni spas kad nemaš ideju' },
    { crew: 'Krastavac', impostor: 'Prisutan svuda a nikad glavna zvezda' },
    { crew: 'Nutella', impostor: 'Zamka za svaku dijetu' },
    { crew: 'Čaj', impostor: 'Mirna alternativa za nemirne dane' },
    { crew: 'Pivo', impostor: 'Razlog da se vikend produži' },
    { crew: 'Musaka', impostor: 'Toplina u tepsiji' },
  ],
};
