import { CategoryData } from '../types';

export const istorija: CategoryData = {
  label: 'Istorija',
  sentences: [
    { crew: 'U kom istorijskom periodu bi voleo da živiš jedan dan?', impostor: 'Iz kog istorijskog perioda bi pobegao posle sat vremena?' },
    { crew: 'Koji istorijski lik bi pozvao na večeru?', impostor: 'Koji istorijski lik bi najmanje želeo kao komšiju?' },
    { crew: 'Da možeš da prisustvuješ jednom istorijskom događaju, kom?', impostor: 'Da možeš da sprečiš jedan istorijski događaj, koji bi bio?' },
    { crew: 'Koji je po tebi najvažniji izum u istoriji?', impostor: 'Koji izum u istoriji je napravio najviše štete?' },
    { crew: 'Koji istorijski lik je po tebi najhrabriji?', impostor: 'Koji istorijski lik je po tebi najlukaviji?' },
    { crew: 'Da si kralj u srednjem veku, kako bi vladao?', impostor: 'Da si pirat u 18. veku, kako bi živeo?' },
    { crew: 'Koji istorijski govor te najviše inspiriše?', impostor: 'Koji istorijski citat koristiš u svakodnevnom životu?' },
    { crew: 'Koji drevni grad bi voleo da posеtiš u njegovom vrhuncu?', impostor: 'Koju drevnu civilizaciju bi voleo da proučavaš?' },
    { crew: 'Da si istoričar, koji period bi proučavao?', impostor: 'Da si arheolog, šta bi tražio?' },
    { crew: 'Koji rat u istoriji misliš da se mogao izbeći?', impostor: 'Koja revolucija u istoriji ti se čini najopravdanijom?' },
    { crew: 'Koji istorijski lik bi bio dobar prijatelj?', impostor: 'Koji istorijski lik bi bio najgori šef?' },
    { crew: 'Da napišeš udžbenik istorije, čemu bi posvetio najviše stranica?', impostor: 'Da snimаš istorijski dokumentarac, šta bi prikazao?' },
    { crew: 'Koji istorijski izum bi voleo da si ti izmislio?', impostor: 'Koji istorijski izum bi voleo da nikad nije napravljen?' },
    { crew: 'Opiši istorijski period koji te najviše fascinira.', impostor: 'Opiši istorijski period o kom znaš najmanje.' },
    { crew: 'Da si vitez na turniru, kako bi se borio?', impostor: 'Da si gladijator u areni, koju strategiju bi koristio?' },
    { crew: 'Koji istorijski mit bi voleo da je istinit?', impostor: 'Koja istorijska „istina" misliš da je zapravo mit?' },
    { crew: 'Koji vladar je po tebi napravio najveću grešku?', impostor: 'Koji vladar je po tebi bio najmudriji?' },
    { crew: 'Da si na Titaniku, šta bi prvo uradio?', impostor: 'Da si na prvom letu na Mesec, šta bi uzeo sa sobom?' },
    { crew: 'Koji istorijski lik bi bio dobar na društvenim mrežama?', impostor: 'Koji istorijski lik bi bio najgori influenser?' },
    { crew: 'Koji istorijski period je po tebi najromantičniji?', impostor: 'Koji istorijski period je po tebi najsuroviji?' },
    { crew: 'Da putujеš kroz vreme, u kom bi pravcu išao?', impostor: 'Da putujеš kroz vreme ali samo možeš da posmatraš, šta bi gledao?' },
    { crew: 'Koji je po tebi najvažniji dan u istoriji?', impostor: 'Koji je po tebi najprecenjeniji dan u istoriji?' },
    { crew: 'Da si osnivač drevnog grada, gde bi ga izgradio?', impostor: 'Da si kapetan broda u 16. veku, kuda bi plovio?' },
    { crew: 'Koji istorijski lik bi voleo da upoznaš na 5 minuta?', impostor: 'Koji istorijski lik bi voleo da ti drži govor na sat vremena?' },
    { crew: 'Koji period mode iz prošlosti bi vratio?', impostor: 'Koji period muzike iz prošlosti bi vratio?' },
    { crew: 'Da si špijun u Hladnom ratu, za koga bi radio?', impostor: 'Da si novinar u Drugom svetskom ratu, šta bi pisao?' },
    { crew: 'Koji drevni recept bi voleo da probaš?', impostor: 'Koji drevni lek bi voleo da testiraš?' },
    { crew: 'Koji istorijski podvig te najviše zadivljuje?', impostor: 'Koji istorijski poraz te najviše rastužuje?' },
    { crew: 'Da si faraon, kakav bi bio tvoj hram?', impostor: 'Da si rimski senator, kakav bi bio tvoj govor?' },
    { crew: 'Opiši istorijsku ličnost koja je bila ispred svog vremena.', impostor: 'Opiši istorijsku ličnost koja je uticala na ceo svet a malo ko zna za nju.' },
    { crew: 'Koji istorijski savez ti se čini najjačim?', impostor: 'Koji istorijski sukob ti se čini najnepotrebnijim?' },
    { crew: 'Da si učesnik industrijаlne revolucije, čime bi se bavio?', impostor: 'Da si učesnik renesanse, čime bi se bavio?' },
    { crew: 'Koja historijska građevina te najviše fascinira?', impostor: 'Koja historijska građevina te najviše plaši?' },
    { crew: 'Da imaš vremensku mašinu za jednu poruku, kome bi je poslao?', impostor: 'Da imaš vremensku mašinu za jednu fotografiju, šta bi slikao?' },
    { crew: 'Koji je po tebi najjači argument za proučavanje istorije?', impostor: 'Koja je po tebi najčešća greška u tumačenju istorije?' },
    { crew: 'Da si diplomata u antičkoj Grčkoj, s kim bi pregovarao?', impostor: 'Da si trgovac na Putu Svile, čime bi trgovao?' },
    { crew: 'Koji istorijski lik bi bio dobar u modernom sportu?', impostor: 'Koji istorijski lik bi bio dobar u modernom biznisu?' },
    { crew: 'Opiši dan u životu srednjovekovnog seljaka.', impostor: 'Opiši dan u životu rimskog vojnika.' },
    { crew: 'Koji istorijski eksperiment te fascinira?', impostor: 'Koje istorijsko otkriće te plaši?' },
    { crew: 'Da si na mestu jednog istorijskog lidera, šta bi drugačije uradio?', impostor: 'Da si savetnik jednog istorijskog lidera, šta bi mu rekao?' },
  ],
  concepts: [
    { crew: 'Kleopatra', impostor: 'Neko ko je vladao šarmom koliko i moći' },
    { crew: 'Gladijator', impostor: 'Neko čiji posao ne bi preživeo u 21. veku' },
    { crew: 'Piramide', impostor: 'Nešto što ljudi i dalje ne mogu da objasne' },
    { crew: 'Rimsko carstvo', impostor: 'Moć koja je mislila da je večna' },
    { crew: 'Vikinzi', impostor: 'Pustolovi koji nisu tražili dozvolu' },
    { crew: 'Kolumbo', impostor: 'Čovek koji je tražio jedno, našao drugo' },
    { crew: 'Renesansa', impostor: 'Kad je svet odlučio da razmišlja ponovo' },
    { crew: 'Troja', impostor: 'Rat koji je počeo zbog pogrešnog razloga' },
    { crew: 'Samuraji', impostor: 'Čast pretvorena u mač' },
    { crew: 'Gutenberg', impostor: 'Čovek koji je razmnožio reči' },
    { crew: 'Berlinski zid', impostor: 'Beton koji je delio ideju' },
    { crew: 'Napoleon', impostor: 'Ambicija u malom pakovanju' },
    { crew: 'Kolosseum', impostor: 'Arena gde je smrt bila zabava' },
    { crew: 'Nikola Tesla', impostor: 'Genije koga je svet shvatio prekasno' },
    { crew: 'Krstaški ratovi', impostor: 'Vera kao izgovor za osvajanje' },
    { crew: 'Mumija', impostor: 'Kad odlazak treba da izgleda lepo' },
    { crew: 'Aleksandar Veliki', impostor: 'Mladost koja je osvojila svet' },
    { crew: 'Stampedo zlata', impostor: 'Kad svi trče na isto mesto' },
    { crew: 'Leonardo da Vinči', impostor: 'Čovek koji je bio dobar u svemu' },
    { crew: 'Titanik', impostor: 'Ponos koji je završio na dnu' },
    { crew: 'Spаrtanci', impostor: 'Trista koji su promenili priču' },
    { crew: 'Mona Liza', impostor: 'Osmeh koji niko ne razume' },
    { crew: 'Ledeno doba', impostor: 'Kad je planet odlučio da se ohladi' },
    { crew: 'Inkvizicija', impostor: 'Pravda koja nije bila pravedna' },
    { crew: 'Svilen put', impostor: 'Drum koji je spojio svetove' },
    { crew: 'Čingis-kan', impostor: 'Osvajač kome nije bio dovoljan horizont' },
    { crew: 'Industrijska revolucija', impostor: 'Kad su mašine uzele posao' },
    { crew: 'Versaj', impostor: 'Kuća napravljena da impresionira' },
    { crew: 'Babilon', impostor: 'Grad koji je hteo da dodirne nebo' },
    { crew: 'Tvrđava', impostor: 'Zidovi koji čuvaju strah unutra' },
    { crew: 'Robinzon Kruso', impostor: 'Samoća koja te natera da budeš kreativan' },
    { crew: 'Stounhendž', impostor: 'Kamenje koje niko nije tražio objašnjenje' },
    { crew: 'Marko Polo', impostor: 'Putnik čijim pričama niko nije verovao' },
    { crew: 'Rimske ceste', impostor: 'Putevi koji su preživeli carstvo' },
    { crew: 'Hijeroglifi', impostor: 'Poruke kojima je trebalo hiljadu godina da se pročitaju' },
    { crew: 'Joan of Arc', impostor: 'Hrabrost koja je plaćena najskuplje' },
    { crew: 'Magellan', impostor: 'Krug oko sveta koji ga je koštao života' },
    { crew: 'Akropolis', impostor: 'Brdo na kome su rođene ideje' },
    { crew: 'Crna kuga', impostor: 'Bolest koja je preoblikovala kontinent' },
    { crew: 'Deklaracija nezavisnosti', impostor: 'Papir koji je pokrenuo naciju' },
  ],
};
