import { CategoryData } from '../types';

export const muzika: CategoryData = {
  label: 'Muzika',
  sentences: [
    { crew: 'Koja pesma ti se vrzmala po glavi ceo prošli mesec?', impostor: 'Koja pesma ti je išla na živce ceo prošli mesec?' },
    { crew: 'Opiši koncert na koji bi odveo nekoga na prvom dejtu.', impostor: 'Opiši koncert sa kog bi pobegao posle pet minuta.' },
    { crew: 'Koji muzičar bi trebalo da dobije nagradu samo za harizmu?', impostor: 'Koji muzičar je po tebi potpuno prenaduvan?' },
    { crew: 'Koja pesma ti uvek popravi raspoloženje?', impostor: 'Koja pesma te uvek rastuži?' },
    { crew: 'Koji je tvoj omiljeni muzički žanr?', impostor: 'Koji muzički žanr nikako ne možeš da slušaš?' },
    { crew: 'Da si u bendu, koji instrument bi svirao?', impostor: 'Da si u bendu, koju ulogu ne bi hteo?' },
    { crew: 'Koja pesma te podseća na detinjstvo?', impostor: 'Koja pesma te podseća na srednju školu?' },
    { crew: 'Koji album bi poneo na pusto ostrvo?', impostor: 'Koji album bi bacio u more?' },
    { crew: 'Koji muzičar pravi najbolje koncerte uživo?', impostor: 'Koji muzičar zvuči bolje na snimku nego uživo?' },
    { crew: 'Da možeš da naučiš jedan instrument za dan, koji bi bio?', impostor: 'Da moraš da zaboraviš jedan instrument zauvek, koji bi bio?' },
    { crew: 'Koja pesma bi bila tvoj hod po crvenom tepihu?', impostor: 'Koja pesma bi bila tvoj alarm za buđenje?' },
    { crew: 'Koji muzičar te iznenađuje koliko je talentovan?', impostor: 'Koji muzičar te iznenađuje koliko je popularan bez talenta?' },
    { crew: 'Opiši savršenu pesmu za vožnju.', impostor: 'Opiši savršenu pesmu za kuvanje.' },
    { crew: 'Koji glas ti je najlepši u muzici?', impostor: 'Koji glas ti je najiritantniji u muzici?' },
    { crew: 'Da pišeš pesmu, o čemu bi bila?', impostor: 'Da režiraš spot, kako bi izgledao?' },
    { crew: 'Koja pesma je savršena za karaoke?', impostor: 'Koju pesmu nikada ne bi pevao na karaokama?' },
    { crew: 'Koji muzički festival bi posetio?', impostor: 'Koji muzički festival te uopšte ne privlači?' },
    { crew: 'Koja pesma te tera da plešeš čak i kad ne želiš?', impostor: 'Koja pesma menja atmosferu čim se pusti?' },
    { crew: 'Koji je po tebi najjači duet u istoriji muzike?', impostor: 'Koji je po tebi najlošiji duet koji su mogli da izaberu?' },
    { crew: 'Da biraš soundtrack za svoj život, ko bi ga komponovao?', impostor: 'Da biraš narátora za svoj život, ko bi pričao?' },
    { crew: 'Koji bend bi ponovo okupio?', impostor: 'Koji bend se dobro raspao i ne treba da se vraća?' },
    { crew: 'Koja pesma ima najbolji uvod?', impostor: 'Koja pesma ima najbolji refren?' },
    { crew: 'Koji muzičar bi bio dobar predsednik?', impostor: 'Koji muzičar bi bio najgori šef?' },
    { crew: 'Opiši pesmu koja te je naterala da plačeš.', impostor: 'Opiši pesmu koja te je naterala da se nasmеješ.' },
    { crew: 'Da možeš da prisustvuješ jednom koncertu iz prošlosti, kom?', impostor: 'Da možeš da izbrišeš jednu pesmu iz istorije, koju?' },
    { crew: 'Koji muzički instrument zvuči najtužnije?', impostor: 'Koji muzički instrument zvuči najradosnije?' },
    { crew: 'Koja pesma je savršena za tuš?', impostor: 'Koja pesma je savršena za trening?' },
    { crew: 'Koji je tvoj omiljeni domaći muzičar?', impostor: 'Koji domaći muzičar te nikad nije oduševio?' },
    { crew: 'Da možeš da čuješ jednu pesmu prvi put ponovo, koja bi bila?', impostor: 'Da moraš da slušaš jednu pesmu 24h, koja bi bila?' },
    { crew: 'Koji žanr muzike te najviše opušta?', impostor: 'Koji žanr muzike te najviše energizuje?' },
    { crew: 'Da otvaraš radio stanicu, kakva bi bila?', impostor: 'Da otvaraš muzički klub, kakav bi bio?' },
    { crew: 'Koja pesma je po tebi potcenjena?', impostor: 'Koja pesma je po tebi precenjena?' },
    { crew: 'Koji je tvoj omiljeni muzički ritam?', impostor: 'Koji muzički ritam nikako ne uhvatiš?' },
    { crew: 'Da praviš plejlistu za žurku, čime bi počeo?', impostor: 'Da praviš plejlistu za spavanje, čime bi počeo?' },
    { crew: 'Koji muzičar bi bio odličan stand-up komičar?', impostor: 'Koji stand-up komičar bi bio odličan muzičar?' },
    { crew: 'Koja pesma je savršena za letnje veče?', impostor: 'Koja pesma je savršena za zimsko jutro?' },
    { crew: 'Koji je tvoj omiljeni muzički trenutak na filmu?', impostor: 'Koji je tvoj omiljeni muzički trenutak na TV-u?' },
    { crew: 'Da upoznaš jednog muzičara, kog bi izabrao?', impostor: 'Da sviraš jednu pesmu pred publikom, koju bi izabrao?' },
    { crew: 'Koji muzičar se najviše promenio tokom karijere?', impostor: 'Koji muzičar uvek zvuči isto a to je OK?' },
    { crew: 'Koja pesma je po tebi savršena?', impostor: 'Koja pesma bi bila savršena da promeni jednu stvar?' },
  ],
  concepts: [
    { crew: 'Gitara', impostor: 'Nešto što može da te rasplače ili razdraži' },
    { crew: 'DJ', impostor: 'Neko ko kontroliše energiju u prostoriji' },
    { crew: 'Karaoke', impostor: 'Aktivnost koja zahteva hrabrost i malo srama' },
    { crew: 'Bubnjevi', impostor: 'Razlog za svađu sa komšijama' },
    { crew: 'Vinil', impostor: 'Nostalgija u fizičkom obliku' },
    { crew: 'Koncert', impostor: 'Mesto gde je normalno da plačeš od sreće' },
    { crew: 'Klavir', impostor: 'Elegancija koja zahteva obe ruke' },
    { crew: 'Refren', impostor: 'Deo koji svi pevaju a ne znaju ostatak' },
    { crew: 'Violina', impostor: 'Tanko a izaziva jake emocije' },
    { crew: 'Bas', impostor: 'Osećaš ga pre nego što ga čuješ' },
    { crew: 'Rok muzika', impostor: 'Bunt koji se prodaje na majicama' },
    { crew: 'Džez', impostor: 'Kad pravila postanu prepreka' },
    { crew: 'Plejlista', impostor: 'Slika tvoje duše u pesama' },
    { crew: 'Mikrofon', impostor: 'Pojačava i glas i sramotu' },
    { crew: 'Festival', impostor: 'Tri dana bez sna i bez žaljenja' },
    { crew: 'Slušalice', impostor: 'Univerzalni znak za "ne uznemiravaj me"' },
    { crew: 'Himna', impostor: 'Pesma koja tera ljude da ustanu' },
    { crew: 'Akustika', impostor: 'Kad skinеš sve ukrase ostane istina' },
    { crew: 'Hip-hop', impostor: 'Priča sa ulice koja je osvojila svet' },
    { crew: 'Melodija', impostor: 'Nešto što zaglavi u glavi danima' },
    { crew: 'Nota', impostor: 'Najmanji deo nečeg velikog' },
    { crew: 'Dirigent', impostor: 'Maše rukama a svi ga slušaju' },
    { crew: 'Harmonika', impostor: 'Svadba nije svadba bez nje' },
    { crew: 'Serenada', impostor: 'Romantika koja zahteva petlje' },
    { crew: 'Uspavanaka', impostor: 'Prva pesma koju si čuo' },
    { crew: 'Pank', impostor: 'Tri akorda i ljutnja na svet' },
    { crew: 'Solo', impostor: 'Trenutak kad svi ćute a jedan govori' },
    { crew: 'Remix', impostor: 'Kad neko promeni tuđe u svoje' },
    { crew: 'Vinilska ploča', impostor: 'Pucketanje koje ljudi plaćaju' },
    { crew: 'Muzički spot', impostor: 'Film od tri minuta koji prodaje pesmu' },
    { crew: 'Verstakt (backstage)', impostor: 'Mesto gde heroji postaju normalni' },
    { crew: 'Autotune', impostor: 'Pomoć koju niko ne priznaje' },
    { crew: 'Turneja', impostor: 'Život u autobusu koji se isplati' },
    { crew: 'Reper', impostor: 'Brzo govori i svi slušaju' },
    { crew: 'Opera', impostor: 'Drama u kojoj svi pevaju umesto da pričaju' },
    { crew: 'Balada', impostor: 'Pesma za treći ples na svadbi' },
    { crew: 'Encore', impostor: 'Kad odеš sa bine ali svi znaju da se vraćaš' },
    { crew: 'Sintisajzer', impostor: 'Zvuk budućnosti iz prošlosti' },
    { crew: 'Muzički producent', impostor: 'Neko iza zavese koga niko ne prepoznaje' },
    { crew: 'Tambura', impostor: 'Tradicija sa žicama' },
  ],
};
