import { CategoryData } from '../types';

export const priroda: CategoryData = {
  label: 'Priroda',
  sentences: [
    { crew: 'Na kom mestu u prirodi se osećaš najsmirenije?', impostor: 'Na kom mestu u prirodi se osećaš najnelagodnije?' },
    { crew: 'Koji prirodni fenomen bi voleo da vidiš uživo?', impostor: 'Koji prirodni fenomen te najviše plaši?' },
    { crew: 'Da si biljka, koja bi bio i zašto?', impostor: 'Da si vremenska pojava, koja bi bio i zašto?' },
    { crew: 'Opiši najlepši zalazak sunca koji si video.', impostor: 'Opiši najlepše noćno nebo koje si video.' },
    { crew: 'Koji je tvoj omiljeni zvuk u prirodi?', impostor: 'Koji zvuk u prirodi te najviše plaši?' },
    { crew: 'Da možeš da živiš pored bilo kog vodenog tela, kog bi izabrao?', impostor: 'Da možeš da živiš na bilo kojoj planini, kojoj?' },
    { crew: 'Koja je tvoja omiljena sezona i zašto?', impostor: 'Koju sezonu bi potpuno ukinuo i zašto?' },
    { crew: 'Opiši najlepši pejzaž koji si video.', impostor: 'Opiši najsuroviji pejzaž koji si video.' },
    { crew: 'Da si istraživač, koji bi bio tvoj san-destinacija?', impostor: 'Da si istraživač, koje mesto nikada ne bi posetio?' },
    { crew: 'Koja biljka te najviše fascinira?', impostor: 'Koja biljka te najviše plaši?' },
    { crew: 'Da možeš da kontrolišeš jednu stihiju, koja bi bila?', impostor: 'Da moraš da preživiš jednu prirodnu katastrofu, koja bi bila?' },
    { crew: 'Koji cvet ti je najlepši?', impostor: 'Koji cvet ti je najiritantniji (alergijaǃ)?' },
    { crew: 'Opiši savršen dan u prirodi.', impostor: 'Opiši najgori dan koji si proveo napolju.' },
    { crew: 'Da pošumljаvaš jedno mesto na svetu, koje bi bilo?', impostor: 'Da isušuješ jedno jezero za kopanje, koje bi bilo?' },
    { crew: 'Koji je tvoj omiljeni nacionalni park?', impostor: 'Koja turistička destinacija u prirodi te razočarala?' },
    { crew: 'Da si reka, gde bi tekao?', impostor: 'Da si vetar, gde bi duvao?' },
    { crew: 'Šta te priroda naučila?', impostor: 'Šta ti se u prirodi čini nepravedno?' },
    { crew: 'Koji je tvoj omiljeni prirodni materijal?', impostor: 'Koji prirodni materijal te iznenađuje svojom čvrstinom?' },
    { crew: 'Opiši najjaču oluju koju si doživeo.', impostor: 'Opiši najtopliji dan koji si doživeo.' },
    { crew: 'Da možeš da gledaš jedan prirodni prizor svaki dan, koji bi bio?', impostor: 'Da moraš da živiš u jednom klimatskom pojasu, koji bi izabrao?' },
    { crew: 'Koji miris u prirodi te najviše smiruje?', impostor: 'Koji miris u prirodi te najviše pokreće?' },
    { crew: 'Da si šumar, u kojoj šumi bi živeo?', impostor: 'Da si okeanograf, koji okean bi istraživao?' },
    { crew: 'Koja te geološka formacija najviše fascinira?', impostor: 'Koji tip zemljišta ti se čini najnegostoljubivijim?' },
    { crew: 'Opiši najlepše jezero koje si video.', impostor: 'Opiši najlepšu plažu koju si video.' },
    { crew: 'Da možeš da posmatraš jedan prirodni proces ubrzano, koji bi bio?', impostor: 'Da možeš da zaustаviš jedan prirodni proces, koji bi bio?' },
    { crew: 'Koje drvo ti je omiljeno?', impostor: 'Koja trava ili žbun ti je omiljeni?' },
    { crew: 'Šta je najčudnija stvar koju si video u prirodi?', impostor: 'Šta je najlepša stvar koju si video u prirodi?' },
    { crew: 'Da si vulkanolog, koji vulkan bi proučavao?', impostor: 'Da si meteorolog, koji fenomen bi pratio?' },
    { crew: 'Koji je tvoj omiljeni tip oblaka?', impostor: 'Koji je tvoj omiljeni tip kiše?' },
    { crew: 'Opiši prirodu svog idealnog mesta za život.', impostor: 'Opiši prirodu mesta koje bi posetio samo jednom.' },
    { crew: 'Da možeš da oživiš jedno izumrlo staništе, koje bi bilo?', impostor: 'Da možeš da stvoriš jedno novo ostrvo, gde bi bilo?' },
    { crew: 'Koji prirodni resurs ti je najvredniji?', impostor: 'Koji prirodni resurs misliš da ćemo prvi potrošiti?' },
    { crew: 'Opiši zvuk šume ujutru.', impostor: 'Opiši zvuk mora uveče.' },
    { crew: 'Da si fotograf prirode, šta bi slikao?', impostor: 'Da si slikar pejzaža, šta bi naslikao?' },
    { crew: 'Koji tip zemljišta te najviše privlači za šetnju?', impostor: 'Koji tip terena te najviše izaziva?' },
    { crew: 'Da imaš baštu, šta bi sadio?', impostor: 'Da imaš staklenik, šta bi gajio?' },
    { crew: 'Koji je po tebi najmoćniji element prirode?', impostor: 'Koji je po tebi najmirniji element prirode?' },
    { crew: 'Opiši savršen prolećni dan.', impostor: 'Opiši savršen jesenji dan.' },
    { crew: 'Da možeš da odeš na safari, gde bi bio?', impostor: 'Da možeš da zaroniš u bilo koji okean, gde bi bilo?' },
    { crew: 'Šta misliš — šuma ili okean, šta je lepše?', impostor: 'Šta misliš — pustinja ili planina, šta je lepše?' },
  ],
  concepts: [
    { crew: 'Vodopad', impostor: 'Prirodna pojava koja privlači turiste' },
    { crew: 'Vulkan', impostor: 'Nešto mirno što može da eksplodira' },
    { crew: 'Duga', impostor: 'Nešto što svi slikaju a niko ne može da uhvati' },
    { crew: 'Munja', impostor: 'Svetlost koja te tera da brojiš' },
    { crew: 'Šuma', impostor: 'Mesto gde tišina ima zvuk' },
    { crew: 'Pesak', impostor: 'Završi svuda gde ne treba' },
    { crew: 'Mesec', impostor: 'Menja oblik ali je uvek isti' },
    { crew: 'Izvor', impostor: 'Početak nečeg velikog, sakriven' },
    { crew: 'Led', impostor: 'Voda koja je odlučila da stane' },
    { crew: 'Koralini greben', impostor: 'Podvodni grad koji niko nije sagradio' },
    { crew: 'Aurora (severna svetlost)', impostor: 'Nebo koje se igra bojama' },
    { crew: 'Pećina', impostor: 'Mrak koji krije priče' },
    { crew: 'Sunčev zrak', impostor: 'Prolazi svuda gde je pozvan' },
    { crew: 'Maslačak', impostor: 'Želja koja leti na vetru' },
    { crew: 'Gejzir', impostor: 'Zemlja koja povremeno izdahne' },
    { crew: 'Plima', impostor: 'Dolazi i odlazi po svom redu' },
    { crew: 'Stena', impostor: 'Trpi vekovima bez žalbe' },
    { crew: 'Glečer', impostor: 'Nešto ogromno a tiho se pomiče' },
    { crew: 'Horizont', impostor: 'Linija do koje nikad ne stigneš' },
    { crew: 'Oaza', impostor: 'Nada usred ničega' },
    { crew: 'Rosa', impostor: 'Jutarnji nakit na travi' },
    { crew: 'Tajga', impostor: 'Beskraj istih stabala' },
    { crew: 'Tornado', impostor: 'Priroda koja se vrti u bes' },
    { crew: 'Delta reke', impostor: 'Kraj puta koji postaje početak' },
    { crew: 'Fosil', impostor: 'Uspomena koju je zemlja sačuvala' },
    { crew: 'Magla', impostor: 'Priroda sakriva ono što je tu' },
    { crew: 'Pustinja', impostor: 'Ništa naokolo a opet živo' },
    { crew: 'Korenje', impostor: 'Snaga koja ne traži pažnju' },
    { crew: 'Vetar', impostor: 'Ne vidiš ga ali pomera sve' },
    { crew: 'Ostrvo', impostor: 'Tačka na mapi koja obećava mir' },
    { crew: 'Kristal', impostor: 'Zemlja koja je odlučila da sija' },
    { crew: 'Lavina', impostor: 'Počinje tiho, završava glasno' },
    { crew: 'Prašuma', impostor: 'Život gde god pogledaš' },
    { crew: 'Zvezdano nebo', impostor: 'Beskonačnost koja te smiruje' },
    { crew: 'Grmljavina', impostor: 'Zvuk za koji niko nije spreman' },
    { crew: 'Cvet', impostor: 'Lepo ali kratko' },
    { crew: 'Morska struja', impostor: 'Nevidljivi put ispod površine' },
    { crew: 'Puzavica', impostor: 'Raste bez dozvole i osvaja sve' },
    { crew: 'Vodopoj', impostor: 'Mesto gde se neprijatelji sretnu u miru' },
    { crew: 'Smena godišnjih doba', impostor: 'Promena koju ne možeš zaustaviti' },
  ],
};
