import { CategoryData } from '../types';

export const sport: CategoryData = {
  label: 'Sport',
  sentences: [
    { crew: 'Koji sport najradije gledaš?', impostor: 'Koji sport najradije igraš?' },
    { crew: 'Ko je po tebi najbolji sportista svih vremena?', impostor: 'Ko je po tebi najprecenjeniji sportista?' },
    { crew: 'Opiši svoj najdraži sportski trenutak.', impostor: 'Opiši najdosadniji sportski meč koji si gledao.' },
    { crew: 'Koji sport bi voleo da naučiš?', impostor: 'Koji sport nikada ne bi probao?' },
    { crew: 'Da si profesionalni sportista, koji sport bi izabrao?', impostor: 'Da si sportski komentator, koji sport bi prenosio?' },
    { crew: 'Koji sportski momenat bi ponovo gledao kao da ga vidiš prvi put?', impostor: 'Koji sportski rezultat te je toliko iznenadio da nisi mogao da veruješ?' },
    { crew: 'Da moraš da treniraš jedan sport profesionalno, koji bi bio?', impostor: 'Da moraš da sudiš jedan sport profesionalno, koji bi bio?' },
    { crew: 'Opiši pravilo u sportu koje ti se čini potpuno besmisleno.', impostor: 'Opiši sport koji bi izmislio da imaš priliku.' },
    { crew: 'Koji tim navijаš od malih nogu?', impostor: 'Koji tim si počeo da mrziš od malih nogu?' },
    { crew: 'Da si selektor reprezentacije, koji bi ti bio prvi potez?', impostor: 'Da si predsednik sportskog kluba, koji bi ti bio prvi potez?' },
    { crew: 'Koji sportista bi bio dobar glumac?', impostor: 'Koji glumac bi bio dobar sportista?' },
    { crew: 'Opiši najluđe sportsko navijanje koje si video.', impostor: 'Opiši najluđi sportski ritual pre meča.' },
    { crew: 'Koji sport je po tebi najopasniji?', impostor: 'Koji sport je po tebi najlakši?' },
    { crew: 'Da igraš za bilo koji tim na svetu, koji bi bio?', impostor: 'Da treniraš bilo koji tim na svetu, koji bi bio?' },
    { crew: 'Koja sportska povreda te najviše zabrinula?', impostor: 'Koji sportski skandal te je najviše šokirao?' },
    { crew: 'Koji je po tebi najlepši stadion?', impostor: 'Koji je po tebi najdosadniji stadion?' },
    { crew: 'Koji sport zahteva najviše talenta?', impostor: 'Koji sport zahteva najviše sreće?' },
    { crew: 'Da imaš dete, koji sport bi mu preporučio?', impostor: 'Da imaš dete, koji sport ne bi želeo da trenira?' },
    { crew: 'Koji sportski dvoboj bi platio da gledaš?', impostor: 'Koji sportski dvoboj bi gledao samo ako je besplatno?' },
    { crew: 'Koji sport je bolji uživo nego na TV-u?', impostor: 'Koji sport je bolji na TV-u nego uživo?' },
    { crew: 'Da biraš jednog saigrača za bilo koji sport, ko bi bio?', impostor: 'Da biraš jednog protivnika za bilo koji sport, ko bi bio?' },
    { crew: 'Koji sport je po tebi najbliži umetnosti?', impostor: 'Koji sport je po tebi najbliži tuči?' },
    { crew: 'Koji sportski trener te je najviše inspirisao?', impostor: 'Koji sportski trener te je najviše nervirao?' },
    { crew: 'Da možeš da prisustvuješ jednom finalu u istoriji, kom?', impostor: 'Da možeš da promeniš ishod jednog finala u istoriji, kog?' },
    { crew: 'Koji sport zaslužuje više pažnje medija?', impostor: 'Koji sport dobija previše medijske pažnje?' },
    { crew: 'Opiši svoju najgoru sportsku povredu.', impostor: 'Opiši svoj najgori sportski promašaj.' },
    { crew: 'Koji sport te najviše fizički umara?', impostor: 'Koji sport te najviše mentalno umara?' },
    { crew: 'Koji sportski komentar ti je ostao u sećanju?', impostor: 'Koja sportska izjava te je najviše nasmejala?' },
    { crew: 'Da organizuješ sportski turnir, koji sport bi bio?', impostor: 'Da organizuješ sportski događaj za zabavu, šta bi osmislio?' },
    { crew: 'Koji sport bi trebalo da bude na Olimpijadi a nije?', impostor: 'Koji sport bi trebalo da se izbaci sa Olimpijade?' },
    { crew: 'Koji sportista ima najbolji mentalitet?', impostor: 'Koji sportista ima najbolji stil?' },
    { crew: 'Koji sport je najbolji za druženje?', impostor: 'Koji sport je najbolji za smršanje?' },
    { crew: 'Da si sportski novinar, šta bi pokrivao?', impostor: 'Da si sportski fotograf, šta bi slikao?' },
    { crew: 'Koji tim ima najlepše dresove?', impostor: 'Koji tim ima najružnije dresove?' },
    { crew: 'Koji sport bi kombinovao sa drugim da napraviš novi?', impostor: 'Koji sport bi potpuno promenio pravila da ga učiniš zanimljivijim?' },
    { crew: 'Koji sportski film je po tebi najbolji?', impostor: 'Koji sportski dokumentarac te je najviše impresionirao?' },
    { crew: 'Da imaš besplatan pristup jednom sportu doživotno, koji bi bio?', impostor: 'Da moraš da se takmičiš u jednom sportu do kraja života, koji bi bio?' },
    { crew: 'Koji sportski rekord te najviše fascinira?', impostor: 'Koji sportski rekord misliš da nikada neće biti oboren?' },
    { crew: 'Da biraš između snage i brzine, šta bi izabrao?', impostor: 'Da biraš između izdržljivosti i preciznosti, šta bi izabrao?' },
    { crew: 'Koji sport bi voleo da gledaš na Mesecu?', impostor: 'Koji sport bi potpuno drugačije funkcionisao u vodi?' },
  ],
  concepts: [
    { crew: 'Fudbal', impostor: 'Razlog za svađu u svakom kafiću' },
    { crew: 'Košarka', impostor: 'Sport gde visina rešava pola posla' },
    { crew: 'Tenis', impostor: 'Borba u tišini sa povremenim aplauzom' },
    { crew: 'Plivanje', impostor: 'Trka u kojoj ne vidiš protivnika' },
    { crew: 'Boks', impostor: 'Plaćeni razlog da nekoga udariš' },
    { crew: 'Penal', impostor: 'Trenutak koji odlučuje sve' },
    { crew: 'Olimpijske igre', impostor: 'Događaj koji se čeka godinama' },
    { crew: 'Dres', impostor: 'Nešto što ljudi nose i kad nisu na terenu' },
    { crew: 'Maraton', impostor: 'Trpljenje pretvoreno u sport' },
    { crew: 'Šah', impostor: 'Rat bez ijednog metka' },
    { crew: 'Skijanje', impostor: 'Spuštanje niz brdo i plaćanje za to' },
    { crew: 'Gol', impostor: 'Razlog za zagrljaj sa strancem' },
    { crew: 'Sudija', impostor: 'Čovek koga svi mrze 90 minuta' },
    { crew: 'Formula 1', impostor: 'Krug za krugom u krug' },
    { crew: 'Golf', impostor: 'Šetnja prerušena u sport' },
    { crew: 'Vaterpolo', impostor: 'Borba za loptu dok guraš vodu' },
    { crew: 'Medalja', impostor: 'Komad metala koji menja život' },
    { crew: 'Trener', impostor: 'Neko ko viče sa strane a ne trči' },
    { crew: 'Crveni karton', impostor: 'Boja koja te šalje kući' },
    { crew: 'Derbi', impostor: 'Meč koji deli grad na pola' },
    { crew: 'Biciklizam', impostor: 'Patnja na dva točka' },
    { crew: 'Ragbi', impostor: 'Fudbal za one koji se ne plaše' },
    { crew: 'Surfovanje', impostor: 'Ples sa nečim što te može progutati' },
    { crew: 'Streljaštvo', impostor: 'Mirnoća pod pritiskom' },
    { crew: 'Hokej', impostor: 'Klizanje sa manje elegancije' },
    { crew: 'Gimnastika', impostor: 'Telo koje ignoriše gravitaciju' },
    { crew: 'Kriket', impostor: 'Sport koji traje duže od filma' },
    { crew: 'Stadion', impostor: 'Mesto gde je normalno da vrištiš' },
    { crew: 'Atletika', impostor: 'Najstarija igra — trči brže' },
    { crew: 'Odbojka', impostor: 'Niko ne sme da pusti da padne' },
    { crew: 'Transfer', impostor: 'Kad lojalnost ima cenu' },
    { crew: 'Navijači', impostor: 'Ljudi koji znaju bolje od trenera' },
    { crew: 'Borilačke veštine', impostor: 'Disciplina prerušena u tuču' },
    { crew: 'Poluvreme', impostor: 'Pauza koja menja planove' },
    { crew: 'Dresovi broj 10', impostor: 'Broj koji nosi odgovornost' },
    { crew: 'Doping', impostor: 'Prečica koja košta sve' },
    { crew: 'Svetsko prvenstvo', impostor: 'Mesec dana kad ceo svet stane' },
    { crew: 'Stoni tenis', impostor: 'Refleksi na malom prostoru' },
    { crew: 'Ronjenje', impostor: 'Tišina u kojoj se takmičiš' },
    { crew: 'Streličarstvo', impostor: 'Preciznost u jednom dahu' },
  ],
};
