import { CategoryData } from '../types';

export const svakodnevica: CategoryData = {
  label: 'Svakodnevica',
  sentences: [
    { crew: 'Šta prvo radiš kad se probudiš ujutru?', impostor: 'Šta zadnje radiš pre nego što zaspiš?' },
    { crew: 'Opiši svoj savršen vikend.', impostor: 'Opiši svoj najgori ponedeljak.' },
    { crew: 'Koji je tvoj guilty pleasure?', impostor: 'Koja je tvoja najgora navika?' },
    { crew: 'Da imaš ceo slobodan dan, šta bi radio?', impostor: 'Da moraš da radiš ceo dan, šta bi birao?' },
    { crew: 'Šta te najviše nervira u svakodnevnom životu?', impostor: 'Šta te najviše usrećuje u svakodnevnom životu?' },
    { crew: 'Kako izgleda tvoje savršeno jutro?', impostor: 'Kako izgleda tvoje tipično jutro?' },
    { crew: 'Koji je tvoj najproduktivniji deo dana?', impostor: 'Koji je tvoj najleniji deo dana?' },
    { crew: 'Šta radiš kad ne možeš da spavaš?', impostor: 'Šta radiš kad imaš previše energije?' },
    { crew: 'Koji zadatak u kući odlažeš najduže?', impostor: 'Koji zadatak u kući uvek uradiš prvi?' },
    { crew: 'Da možeš da automatizuješ jednu stvar u životu, šta bi bilo?', impostor: 'Da moraš da radiš jednu stvar ručno zauvek, šta bi bilo?' },
    { crew: 'Koji zvuk te budi bolje od alarma?', impostor: 'Koji zvuk te uspavljuje bolje od bilo čega?' },
    { crew: 'Šta je prva stvar koju uzmeš kad izlaziš iz kuće?', impostor: 'Šta je prva stvar koju skineš kad uđeš u kuću?' },
    { crew: 'Opiši savršenu pauzu na poslu.', impostor: 'Opiši najgoru stvar na poslu.' },
    { crew: 'Koji je tvoj rituаl za opuštanje posle napornog dana?', impostor: 'Koji je tvoj ritual za motivaciju na početku dana?' },
    { crew: 'Da možeš da dodaš jedan sat danu, za šta bi ga koristio?', impostor: 'Da moraš da izbaciš jednu aktivnost iz dana, koju bi izbacio?' },
    { crew: 'Šta ti oduzima najviše vremena a ne bi trebalo?', impostor: 'Šta ti oduzima najmanje vremena a donosi najviše radosti?' },
    { crew: 'Opiši savršen kišni dan kod kuće.', impostor: 'Opiši savršen sunčan dan napolju.' },
    { crew: 'Koji predmet koristiš svaki dan a retko razmišljaš o njemu?', impostor: 'Koji predmet si kupio a nikada ne koristiš?' },
    { crew: 'Šta najčešće zaboraviš?', impostor: 'Šta nikad ne zaboraviš?' },
    { crew: 'Koji je tvoj najjači life hack?', impostor: 'Koji je tvoj najgluplji life hack koji zapravo radi?' },
    { crew: 'Šta radiš u redu za čekanje?', impostor: 'Šta radiš kad čekaš nekoga ko kasni?' },
    { crew: 'Kako se nagrađuješ posle teškog dana?', impostor: 'Kako se kažnjavaš kad prokrastiniraš?' },
    { crew: 'Koji je tvoj omiljeni deo nedelje?', impostor: 'Koji je tvoj najgori deo nedelje?' },
    { crew: 'Da moraš da žrtvuješ jednu modernu pogodnost, šta bi bilo?', impostor: 'Da moraš da se vratiš jednoj staroj navici, koja bi bila?' },
    { crew: 'Šta uvek imaš u džepu?', impostor: 'Šta uvek imaš u rancu ili torbi?' },
    { crew: 'Koji je tvoj omiljeni miriš u kući?', impostor: 'Koji miris te odmah vraća u neko sećanje?' },
    { crew: 'Šta te motiviše da ustaneš iz kreveta?', impostor: 'Šta te tera da ostaneš u krevetu?' },
    { crew: 'Da moraš da odustaneš od društvenih mreža ili TV-a, šta bi bilo?', impostor: 'Da moraš da odustaneš od kafe ili slatkiša, šta bi bilo?' },
    { crew: 'Koja sitna stvar ti popravlja dan?', impostor: 'Koja sitna stvar ti pokvari ceo dan?' },
    { crew: 'Opiši savršen nedeljni ručak.', impostor: 'Opiši savršenu petak veče.' },
    { crew: 'Šta radiš dok čekaš da voda proključa?', impostor: 'Šta radiš dok čekaš da se telefon napuni?' },
    { crew: 'Koji je tvoj omiljeni način prevoza?', impostor: 'Koji je tvoj najgori način prevoza?' },
    { crew: 'Šta ti je najteže da održavaš urednim?', impostor: 'Šta ti je najlakše da održavaš urednim?' },
    { crew: 'Da možeš da delegiraš jedan zadatak zauvek, koji bi bio?', impostor: 'Da moraš da učiš jedan novi zadatak, koji bi bio?' },
    { crew: 'Opiši savršen radni prostor.', impostor: 'Opiši najgori radni prostor u kom si radio.' },
    { crew: 'Šta bi promenio u svojoj dnevnoj rutini?', impostor: 'Šta nikad ne bi promenio u svojoj dnevnoj rutini?' },
    { crew: 'Koji je tvoj omiljeni sezonski ritual?', impostor: 'Koje godišnje doba te najviše usporava?' },
    { crew: 'Da možeš da živiš na bilo kom mestu, gde bi bio?', impostor: 'Da moraš da se seliš sutra, gde ne bi otišao?' },
    { crew: 'Šta te najviše smiruje kad si pod stresom?', impostor: 'Šta te najviše stresira a ne bi trebalo?' },
    { crew: 'Da piše knjiga o tvom tipičnom danu, koji bi bio naslov?', impostor: 'Da snimaš vlog o svom danu, šta bi izostavio?' },
  ],
  concepts: [
    { crew: 'Buđenje alarma', impostor: 'Zvuk koji svako mrzi ali mu veruje' },
    { crew: 'Vožnja autobusom', impostor: 'Vreme koje ni za šta ne koristiš' },
    { crew: 'Kuvanje ručka', impostor: 'Obaveza koja ponekad postane umetnost' },
    { crew: 'Pranje zuba', impostor: 'Nešto što radiš dva puta dnevno bez razmišljanja' },
    { crew: 'Šetnja', impostor: 'Najjednostavniji lek za glavu' },
    { crew: 'Tuš', impostor: 'Mesto gde dobijaš najbolje ideje' },
    { crew: 'Ključevi', impostor: 'Uvek na pogrešnom mestu' },
    { crew: 'Pranje sudova', impostor: 'Posao koji nikad nije gotov' },
    { crew: 'Usisavanje', impostor: 'Zvuk koji životinju tera u panik' },
    { crew: 'Peglanje', impostor: 'Aktivnost za koju niko nema živce' },
    { crew: 'Jutarnja kafa', impostor: 'Ritual pre svih rituala' },
    { crew: 'Gužva u saobraćaju', impostor: 'Vreme koje ti ukradu bez izvinjenja' },
    { crew: 'Daljinski upravljač', impostor: 'Nestane kad ti zatreba' },
    { crew: 'WiFi šifra', impostor: 'Prvo pitanje u svakoj kući' },
    { crew: 'Punjač za telefon', impostor: 'Nešto za šta se uvek trkate' },
    { crew: 'Nedeljna šetnja', impostor: 'Izgovor da se ne radi ništa korisno' },
    { crew: 'Lista za kupovinu', impostor: 'Nešto što napišeš i zaboraviš kod kuće' },
    { crew: 'Odlaganje obaveza', impostor: 'Veština u kojoj si profesionalac' },
    { crew: 'Subotnje jutro', impostor: 'Jedino jutro bez krivice' },
    { crew: 'Komšija', impostor: 'Neko koga trpiš jer deli zid sa tobom' },
    { crew: 'Lift', impostor: 'Mesto za najneprijatnije tišine' },
    { crew: 'Kućni papuče', impostor: 'Sloboda za stopala' },
    { crew: 'Budilnik', impostor: 'Neprijatelj koji ti pomaže' },
    { crew: 'Frižider', impostor: 'Otvoriš ga bez razloga, zatvoriš razočaran' },
    { crew: 'Dušek', impostor: 'Investicija u koju ne razmišljaš dovoljno' },
    { crew: 'Pranje veša', impostor: 'Nikad se ne završava' },
    { crew: 'Odeća za krevet', impostor: 'Sloboda prerušena u pidžamu' },
    { crew: 'Ponedeljak', impostor: 'Dan koji niko nije tražio' },
    { crew: 'Vikend plan', impostor: 'Nešto što se uvek promeni' },
    { crew: 'Šoping', impostor: 'Terapija sa posledicama' },
    { crew: 'Telefonski poziv', impostor: 'Nešto što izbegavaš koliko možeš' },
    { crew: 'Pauza za ručak', impostor: 'Najkraćih 30 minuta u danu' },
    { crew: 'Kašnjenje', impostor: 'Navika za koju uvek imaš izgovor' },
    { crew: 'Ostavljanje čarapa', impostor: 'Uvek nestane jedna' },
    { crew: 'Parkiranje', impostor: 'Takmičenje za koje nema medalja' },
    { crew: 'Dremmka', impostor: 'Pet minuta koji traju sat' },
    { crew: 'Plaćanje računa', impostor: 'Razlog za tišinu na kraju meseca' },
    { crew: 'Nedeljni red vožnje', impostor: 'Nešto čemu veruješ ali te izneveri' },
    { crew: 'Porodični ručak', impostor: 'Ljubav izražena kroz obavezno prisustvo' },
    { crew: 'Promena sata', impostor: 'Sat koji dobiješ ili izgubiš ali ne osetiš' },
  ],
};
