import { CategoryData } from '../types';

export const tehnologija: CategoryData = {
  label: 'Tehnologija',
  sentences: [
    { crew: 'Koja aplikacija ti je promenila svakodnevnu rutinu?', impostor: 'Koju aplikaciju si obrisao jer te previše odvlačila?' },
    { crew: 'Da možeš da izumiš jedan gadget, šta bi radio?', impostor: 'Da možeš da uništiš jedan gadget zauvek, koji bi bio?' },
    { crew: 'Opiši najkorisniju funkciju svog telefona.', impostor: 'Opiši najbesmileniju funkciju svog telefona.' },
    { crew: 'Koji je tvoj omiljeni gadget koji koristiš svaki dan?', impostor: 'Koji gadget si kupio a nikad ne koristiš?' },
    { crew: 'Da možeš da vratiš jednu staru tehnologiju, koja bi bila?', impostor: 'Da možeš da ubrzaš jednu buduću tehnologiju, koja bi bila?' },
    { crew: 'Koji sajt posećuješ svaki dan?', impostor: 'Koji sajt si blokirao da ne bi gubio vreme?' },
    { crew: 'Da si programer, kakvu aplikaciju bi napravio?', impostor: 'Da si dizajner, kakav sajt bi napravio?' },
    { crew: 'Koje podešavanje na telefonu ti je promenilo život?', impostor: 'Koje podešavanje na telefonu nikada nisi menjao?' },
    { crew: 'Koji je tvoj omiljeni video na internetu?', impostor: 'Koji video na internetu te je najviše zbunio?' },
    { crew: 'Da moraš da se odrekneš jedne društvene mreže, koja bi bila?', impostor: 'Da moraš da koristiš samo jednu društvenu mrežu, koja bi bila?' },
    { crew: 'Opiši budućnost tehnologije za 20 godina.', impostor: 'Opiši tehnologiju iz prošlosti koja ti nedostaje.' },
    { crew: 'Koji je tvoj omiljeni prečac na tastaturi?', impostor: 'Koja funkcija računara te najviše frustrira?' },
    { crew: 'Da možeš da hakuješ jedan sistem (legalno), koji bi bio?', impostor: 'Da moraš da zašttitiš jedan sistem, koji bi bio?' },
    { crew: 'Koji je po tebi najbolji operativni sistem?', impostor: 'Koji je po tebi najgori operativni sistem?' },
    { crew: 'Da praviš robota, šta bi radio?', impostor: 'Da praviš AI asistenta, u čemu bi bio specijalizovan?' },
    { crew: 'Koja igrica ti je oduzela najviše vremena u životu?', impostor: 'Koju igricu si pokušao da voliš ali nisi mogao?' },
    { crew: 'Šta misliš o veštačkoj inteligenciji?', impostor: 'Šta misliš o kripto valutama?' },
    { crew: 'Koji je tvoj omiljeni tip notifikacije?', impostor: 'Koja notifikacija te najviše nervira?' },
    { crew: 'Da možeš da resetuješ jednu stvar u životu kao na kompjuteru, šta bi bilo?', impostor: 'Da možeš da copy-paste jednu veštinu od nekog, koju bi izabrao?' },
    { crew: 'Koji online alat koristiš koji većina ljudi ne zna?', impostor: 'Koji popularan online alat nikada nisi razumeo?' },
    { crew: 'Opiši svoju idealnu pametnu kuću.', impostor: 'Opiši najlošiji pametni uređaj koji si koristio.' },
    { crew: 'Da si Elon Musk jedan dan, šta bi uradio?', impostor: 'Da si osnivač Googlea jedan dan, šta bi uradio?' },
    { crew: 'Koji telefon si imao kao prvi?', impostor: 'Koji kompjuter si imao kao prvi?' },
    { crew: 'Šta bi bila tvoja poslednja Google pretraga?', impostor: 'Šta bi bila tvoja najčudnija Google pretraga?' },
    { crew: 'Da praviš startap, kakav bi bio?', impostor: 'Da investiraš u startap, kakav bi izabrao?' },
    { crew: 'Koji je po tebi najkorisniji izum u istoriji?', impostor: 'Koji je po tebi najštetniji izum u istoriji?' },
    { crew: 'Opiši savršenu video igru.', impostor: 'Opiši savršenu mobilnu igru.' },
    { crew: 'Da možeš da instaliraš čip u mozak, šta bi radio?', impostor: 'Da možeš da upload-uješ znanje u mozak, šta bi učio?' },
    { crew: 'Koji streaming servis koristiš najviše?', impostor: 'Koji streaming servis bi ugasio?' },
    { crew: 'Da praviš sajt, o čemu bi bio?', impostor: 'Da praviš podcast, o čemu bi bio?' },
    { crew: 'Koja tehnološka kompanija te najviše inspiriše?', impostor: 'Koja tehnološka kompanija te najviše nervira?' },
    { crew: 'Da živiš u simulaciji, šta bi bio prvi znak?', impostor: 'Da živiš u video igri, koji žanr bi bio?' },
    { crew: 'Koji je tvoj omiljeni feature na pametnom satu?', impostor: 'Koji je tvoj omiljeni feature na bežičnim slušalicama?' },
    { crew: 'Da moraš da koristiš samo jednu aplikaciju na telefonu, koja bi bila?', impostor: 'Da moraš da izbrišeš sve osim tri aplikacije, koje bi ostale?' },
    { crew: 'Koji internet trend ti je bio najsmešniji?', impostor: 'Koji internet trend si najmanje razumeo?' },
    { crew: 'Opiši najgori tehnički problem koji si imao.', impostor: 'Opiši najgluplji način na koji si pokvario uređaj.' },
    { crew: 'Da možeš da teleportuješ podatke u prošlost, šta bi poslao?', impostor: 'Da možeš da primiš poruku iz budućnosti, šta bi želeo da piše?' },
    { crew: 'Koji emoji koristiš najčešće?', impostor: 'Koji emoji nikad ne koristiš a trebalo bi?' },
    { crew: 'Da si IT podrška za jedan dan, šta bi promenio?', impostor: 'Da si haker za jedan dan, šta bi istražio?' },
    { crew: 'Koja tehnologija te plaši?', impostor: 'Koja tehnologija te najviše uzbuđuje?' },
  ],
  concepts: [
    { crew: 'WiFi', impostor: 'Nešto bez čega paniči ceo hotel' },
    { crew: 'Screenshot', impostor: 'Dokaz koji ne možeš da porekneš' },
    { crew: 'Bluetooth', impostor: 'Nešto što nikad ne radi iz prvog pokušaja' },
    { crew: 'Password', impostor: 'Nešto što stalno zaboravljaš a od toga zavisi sve' },
    { crew: 'Update', impostor: 'Dolazi kad ti najmanje treba' },
    { crew: 'Laptop', impostor: 'Prenosiva kancelarija koja greje kolena' },
    { crew: 'Selfie', impostor: 'Autoportret za digitalno doba' },
    { crew: 'Email', impostor: 'Pismo koje niko ne čita do kraja' },
    { crew: 'USB', impostor: 'Uvek ga okrеneš pogrešno prvi put' },
    { crew: 'Dark mode', impostor: 'Spas za oči u 2 ujutru' },
    { crew: 'Ctrl+Z', impostor: 'Supemoć koju želiš u stvarnom životu' },
    { crew: 'Cloud', impostor: 'Nešto nevidljivo čemu veruješ podatke' },
    { crew: 'Notifikacija', impostor: 'Zvuk koji kontroliše tvoj dan' },
    { crew: 'Baterija na 1%', impostor: 'Panika u jednom broju' },
    { crew: 'VPN', impostor: 'Nevidljivi plašt za internet' },
    { crew: 'Google', impostor: 'Zna više o tebi nego ti sam' },
    { crew: 'Caps Lock', impostor: 'Slučajno VIKANJE' },
    { crew: 'Spam', impostor: 'Poruke od ljudi koji te ne poznaju' },
    { crew: 'Mim', impostor: 'Humor sa rokom trajanja' },
    { crew: 'Loading', impostor: 'Krug koji te tera da sumnjaš u sve' },
    { crew: 'Kursor', impostor: 'Treperi i čeka da nešto uradiš' },
    { crew: 'Pop-up reklama', impostor: 'Nešto što zatvoriš pre nego što pročitaš' },
    { crew: 'Touchscreen', impostor: 'Staklo na kome živiš' },
    { crew: 'Viralan video', impostor: 'Nešto glupo što ceo svet gleda' },
    { crew: 'Alexa', impostor: 'Prisluškivač kome si dao dozvolu' },
    { crew: 'QR kod', impostor: 'Crno-beli lavirint za kameru' },
    { crew: 'Pixel', impostor: 'Najmanja tačka velike slike' },
    { crew: 'Selfie štap', impostor: 'Izum koji je promashio ali je preživeo' },
    { crew: 'GPS', impostor: 'Glas koji te vodi ali ponekad laže' },
    { crew: 'AirPods', impostor: 'Kad ne čuješ svet ali izgledaš kul' },
    { crew: 'TikTok algoritam', impostor: 'Nešto što te poznaje bolje od prijatelja' },
    { crew: 'Ctrl+C Ctrl+V', impostor: 'Najčešći pokret na tastaturi' },
    { crew: 'Error 404', impostor: 'Razočaranje u brojevima' },
    { crew: 'Podcast', impostor: 'Radio koji se prilagodio novom dobu' },
    { crew: 'Emoji', impostor: 'Kad ti reči nisu dovoljne ali ni slike' },
    { crew: 'Siri', impostor: 'Pitаš je nešto, odgovori ti nešto drugo' },
    { crew: 'Smartwatch', impostor: 'Sat koji radi sve osim da ti kaže vreme' },
    { crew: 'Instagram filter', impostor: 'Maska koju biraš sam' },
    { crew: 'Streaming', impostor: 'Kad gledаš ali ništa ne poseduješ' },
    { crew: 'Bitcoin', impostor: 'Novac u koji veruješ ali ne razumeš' },
  ],
};
