import { CategoryData } from '../types';

export const zivotinje: CategoryData = {
  label: 'Životinje',
  sentences: [
    { crew: 'Koja je tvoja omiljena životinja?', impostor: 'Koje životinje se najviše plašiš?' },
    { crew: 'Da možeš da imaš bilo koju životinju kao ljubimca, koju bi izabrao?', impostor: 'Da možeš da budeš bilo koja životinja jedan dan, koja bi bio?' },
    { crew: 'Opiši najsmešniju stvar koju si video da životinja radi.', impostor: 'Opiši najčudniju životinju koju si ikada video.' },
    { crew: 'Koja životinja te podseća na sebe?', impostor: 'Koja životinja te podseća na svog najboljeg druga?' },
    { crew: 'Da imaš farmu, koje životinje bi držao?', impostor: 'Da imaš zoo vrt, koje životinje bi imao?' },
    { crew: 'Koja životinja je po tebi najinteligentnija?', impostor: 'Koja životinja je po tebi najpotcenjenija?' },
    { crew: 'Da možeš da razgovaraš sa jednom životinjom, koja bi bila?', impostor: 'Da možeš da razumeš jednu životinju bez reči, koja bi bila?' },
    { crew: 'Koji kućni ljubimac je najbolji za stan?', impostor: 'Koji kućni ljubimac je najbolji za kuću sa dvorištem?' },
    { crew: 'Opiši najsrećnijeg psa koji ti pada na pamet.', impostor: 'Opiši najsrećniju mačku koja ti pada na pamet.' },
    { crew: 'Koja životinja ima najlepši zvuk?', impostor: 'Koja životinja ima najiritirantniji zvuk?' },
    { crew: 'Da si veterinar, koju vrstu životinja bi lečio?', impostor: 'Da si biolog, koju vrstu životinja bi proučavao?' },
    { crew: 'Koja životinja bi bila najbolji prijatelj u apokalipsi?', impostor: 'Koja životinja bi bila najgori neprijatelj u apokalipsi?' },
    { crew: 'Koji je tvoj omiljeni dokumentarac o životinjama?', impostor: 'Koji crtani film o životinjama ti je omiljeni?' },
    { crew: 'Da životinje mogu da glasaju, koja bi bila predsednik?', impostor: 'Da životinje imaju školu, koja bi bila profesor?' },
    { crew: 'Koja životinja je po tebi najvernija?', impostor: 'Koja životinja je po tebi najlukavija?' },
    { crew: 'Koji insekt te najviše plaši?', impostor: 'Koji insekt te najviše fascinira?' },
    { crew: 'Koja morska životinja bi voleo da vidiš uživo?', impostor: 'Koja morska životinja ti se čini najstrašnijom?' },
    { crew: 'Da možeš da imaš sposobnost bilo koje životinje, koju bi izabrao?', impostor: 'Da moraš da živiš životom jedne životinje mesec dana, koju bi izabrao?' },
    { crew: 'Koja životinja bi bila najbolji vozač?', impostor: 'Koja životinja bi bila najgori vozač?' },
    { crew: 'Opiši životinju koja te nervira a svi je obožavaju.', impostor: 'Opiši životinju koju obožavaš a svi je se plaše.' },
    { crew: 'Koja životinja je po tebi najfotogeničnija?', impostor: 'Koja životinja je po tebi najnefotogeničnija?' },
    { crew: 'Da praviš tim od životinja, koje bi izabrao?', impostor: 'Da praviš bend od životinja, koje bi izabrao?' },
    { crew: 'Koja životinja je po tebi najčistija?', impostor: 'Koja životinja je po tebi najhaotičnija?' },
    { crew: 'Koji je najsmešniji nadimak za psa koji si čuo?', impostor: 'Koji je najsmešniji nadimak za mačku koji si čuo?' },
    { crew: 'Koja životinja te iznenađuje koliko je brza?', impostor: 'Koja životinja te iznenađuje koliko je spora?' },
    { crew: 'Da životinje drže olimpijadu, koja bi sport bila šampion?', impostor: 'Da životinje drže takmičenje u lepoti, koja bi pobedila?' },
    { crew: 'Koju životinju bi voleo da vidiš u divljini?', impostor: 'Koju životinju ne bi voleo da sretneš u divljini?' },
    { crew: 'Da si životinja u crtanom filmu, koja bi bio?', impostor: 'Da si životinja u horor filmu, koja bi bio?' },
    { crew: 'Koja životinja spava na najčudniji način?', impostor: 'Koja životinja jede na najčudniji način?' },
    { crew: 'Koji je po tebi najlepši zvuk prirode koji životinja pravi?', impostor: 'Koji je po tebi najčudniji način na koji životinja komunicira?' },
    { crew: 'Da imaš ribnjak, koje ribe bi imao?', impostor: 'Da imaš terarijum, koje životinje bi držao?' },
    { crew: 'Koja životinja te leči samo pogledom?', impostor: 'Koja životinja te nasmeje samo pogledom?' },
    { crew: 'Koji je najjači životinjski roditelj?', impostor: 'Koji je najgori životinjski roditelj?' },
    { crew: 'Koja životinja preživljava sve?', impostor: 'Koja životinja ne bi preživela ni dan u tvom životu?' },
    { crew: 'Da možeš da prolaziš kroz život sa jednom životinjom, koja bi bila?', impostor: 'Da moraš da čuvaš jednu životinju 24 sata, koja bi bila najteža?' },
    { crew: 'Koja životinja je po tebi najelegantija?', impostor: 'Koja životinja je po tebi najnespretija?' },
    { crew: 'Koji je tvoj omiljeni životinjski par?', impostor: 'Koja dva životinjska neprijatelja te najviše zabavljaju?' },
    { crew: 'Da životinje imaju Instagram, čiji bi imao najviše pratilaca?', impostor: 'Da životinje imaju YouTube kanal, čiji bi bio najdosadniji?' },
    { crew: 'Koja životinja je po tebi najhrabrija?', impostor: 'Koja životinja je po tebi najplašljivija?' },
    { crew: 'Da možeš da spaseš jednu ugroženu vrstu, koja bi bila?', impostor: 'Da moraš da živiš sa jednom divljom životinjom, koju bi izabrao?' },
  ],
  concepts: [
    { crew: 'Pas', impostor: 'Vernost bez uslova' },
    { crew: 'Delfin', impostor: 'Osmeh koji ne skida s lica' },
    { crew: 'Orao', impostor: 'Sloboda gledana odozgo' },
    { crew: 'Mačka', impostor: 'Bira te ona, ne ti nju' },
    { crew: 'Lav', impostor: 'Spava 20 sati a svi ga se plaše' },
    { crew: 'Slon', impostor: 'Nikad ne zaboravlja' },
    { crew: 'Medved', impostor: 'Zagrljaj koji nije preporučljiv' },
    { crew: 'Zmija', impostor: 'Nema noge a brža je od tebe' },
    { crew: 'Sova', impostor: 'Mudrost koja ne spava noću' },
    { crew: 'Kornjača', impostor: 'Nosi kuću na leđima' },
    { crew: 'Panda', impostor: 'Lenjost koja osvaja srca' },
    { crew: 'Vuk', impostor: 'Timski igrač koji uliva strah' },
    { crew: 'Hobotnica', impostor: 'Osam razloga da se skrije' },
    { crew: 'Papagaj', impostor: 'Ponavlja ali ne razume' },
    { crew: 'Kameleon', impostor: 'Prilagođava se, ali uvek laže' },
    { crew: 'Jež', impostor: 'Nežan ali se ne možeš približiti' },
    { crew: 'Flamingo', impostor: 'Stoji na jednoj nozi i izgleda fabulous' },
    { crew: 'Pingvin', impostor: 'Odjeven za svečanost, živi na ledu' },
    { crew: 'Ajkula', impostor: 'Milioni godina bez promene posla' },
    { crew: 'Pshenica... wait, Pčela', impostor: 'Mala a od nje zavisi sve' },
    { crew: 'Lisica', impostor: 'Lukavost na četiri noge' },
    { crew: 'Žirafa', impostor: 'Perspektiva koju niko drugi nema' },
    { crew: 'Hrčak', impostor: 'Trči u krug ali deluje zadovoljan' },
    { crew: 'Leopard', impostor: 'Elegancija koja ubija' },
    { crew: 'Golub', impostor: 'Niko ga ne voli a svuda je' },
    { crew: 'Krokodil', impostor: 'Čeka strpljivo, udara jednom' },
    { crew: 'Labud', impostor: 'Lep odozgo, haotičan ispod površine' },
    { crew: 'Mrav', impostor: 'Nosi više nego što izgleda moguće' },
    { crew: 'Kit', impostor: 'Tih džin koji peva' },
    { crew: 'Koala', impostor: 'Spava ceo dan i svi ga obožavaju' },
    { crew: 'Leptir', impostor: 'Lep ali traje kratko' },
    { crew: 'Nilski konj', impostor: 'Izgleda smešno, ali je opasan' },
    { crew: 'Zec', impostor: 'Brzina i slatkoća u jednom paketu' },
    { crew: 'Orao', impostor: 'Pogled koji vidi sve' },
    { crew: 'Kamila', impostor: 'Preživljava bez onoga što svima treba' },
    { crew: 'Rakun', impostor: 'Lopov sa maskom na licu' },
    { crew: 'Pelikаn', impostor: 'Džep koji gutа sve' },
    { crew: 'Noj', impostor: 'Ne leti, ali ne znaš da mu priđeš' },
    { crew: 'Morski konjic', impostor: 'Tata koji radi mamin posao' },
    { crew: 'Svitac', impostor: 'Noćno svetlo koje se ne gasi' },
  ],
};
